"""
Drive NLP Question-Answer Engine
=================================
Answers plain-English questions about the current drive's SMART data using Gemini AI.

Design
------
- Uses Google Gemini API to generate context-aware answers.
- Bounds the Gemini API to only answer questions related to SSD/HDD health and this project.
"""

import os
import google.generativeai as genai
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

class DriveNlpEngine:
    """
    NLP engine that answers drive health questions using the
    current SMART summary as context and Gemini as the LLM.
    """
    
    def __init__(self):
        self.api_key = os.getenv("GEMINI_API_KEY")
        if self.api_key:
            genai.configure(api_key=self.api_key)
            self.model = genai.GenerativeModel('gemini-2.5-flash')
        else:
            self.model = None

    def answer(self, question: str, smart: dict) -> str:
        """
        Answer a plain-English question about the drive.

        Parameters
        ----------
        question : str
            User's question.
        smart : dict
            SMART summary dict.

        Returns
        -------
        str
            Short, plain-English answer generated by Gemini.
        """
        if not self.model:
            return "Error: GEMINI_API_KEY is not set in the .env file. Please configure it to use the AI Q&A feature."

        context = (
            f"You are a specialized AI assistant for the 'SSD Health Checker' project. "
            f"Your sole purpose is to answer questions strictly related to drive health, SMART data, "
            f"and the specific status of the user's drive.\n\n"
            f"Current Drive Context:\n"
            f"- Model: {smart.get('model', 'Unknown')}\n"
            f"- Health: {smart.get('health_percent', 'Unknown')}%\n"
            f"- Temperature: {smart.get('temp_c', 'Unknown')} C\n"
            f"- Power-on Hours: {smart.get('power_on_hours', 'Unknown')}\n"
            f"- Unsafe Shutdowns: {smart.get('unsafe_shutdowns', 0)}\n"
            f"- Reallocated Sectors: {smart.get('reallocated_sectors', 0)}\n"
            f"- Pending Sectors: {smart.get('pending_sectors', 0)}\n"
            f"- Uncorrectable Sectors: {smart.get('uncorrectable_sectors', 0)}\n"
            f"- AI Label: {smart.get('ai_label', 'Unknown')}\n"
            f"- AI Confidence: {smart.get('ai_confidence', 'Unknown')}\n"
            f"- AI Reason: {smart.get('ai_reason', 'Unknown')}\n\n"
            f"User Question: {question}\n\n"
            f"Instructions:\n"
            f"1. Keep the answer short and clear (1-3 sentences maximum).\n"
            f"2. Use the provided drive context to make the answer specific to this drive.\n"
            f"3. Do NOT answer any questions unrelated to SSD/HDD health, storage, or the 'SSD Health Checker' project. If asked an unrelated question, politely decline.\n"
        )
        
        try:
            response = self.model.generate_content(context)
            if response.text:
                return response.text.strip()
            return "Error: Gemini returned an empty response."
        except Exception as e:
            return f"An error occurred while fetching the answer from Gemini: {str(e)}"
